[package]
name = "sqlite-ll"
version = "0.1.0"
authors = [
    "John-John Tedro <udoprog@tedro.se>"
]
edition = "2021"
rust-version = "1.87"
description = "Low-level interface to the SQLite database"
documentation = "https://docs.rs/sqlite-ll"
readme = "README.md"
homepage = "https://github.com/udoprog/sqlite-ll"
repository = "https://github.com/udoprog/sqlite-ll"
license = "MIT OR Apache-2.0"
keywords = ["database"]
categories = ["api-bindings", "database"]

[features]
default = ["alloc", "linkage"]
std = ["alloc"]
alloc = []
linkage = ["sqlite3-sys/linkage"]

[dependencies.sqlite3-sys]
version = "0.18.0"
default-features = false

[dev-dependencies]
anyhow = "1.0.100"
criterion = "0.8.0"
tempfile = "3.24.0"

[[bench]]
name = "statement_benches"
harness = false
