[package]
name = "sqll"
version = "0.1.0"
authors = [
    "John-John Tedro <udoprog@tedro.se>"
]
edition = "2024"
rust-version = "1.87"
description = "Usable low-level interface to sqlite that doesn't get in your way"
documentation = "https://docs.rs/sqll"
readme = "README.md"
homepage = "https://github.com/udoprog/sqll"
repository = "https://github.com/udoprog/sqll"
license = "MIT OR Apache-2.0"
keywords = ["database"]
categories = ["api-bindings", "database"]

[features]
default = ["alloc", "linkage"]
std = ["alloc"]
alloc = []
linkage = ["sqlite3-sys/linkage"]

[dependencies.sqlite3-sys]
version = "0.18.0"
default-features = false

[dev-dependencies]
anyhow = "1.0.100"
criterion = "0.8.0"
tempfile = "3.24.0"

[[bench]]
name = "statement_benches"
harness = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
